(defun setup ()
  (init-window 800 600 "Quicle Native"))

(defun draw ()
  (begin-drawing)
  (clear-background #x000000FF)
  (let ((mx (get-mouse-x))
        (my (get-mouse-y)))
    (draw-circle mx my 20.0))
  (end-drawing))
